// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-_45MCA4Iu0Wnrv_YX7M5GRdGBrm_1C8',
    appId: '1:453213686433:web:71238553aa31bd983b7ee0',
    messagingSenderId: '453213686433',
    projectId: 'katkot-5c23e',
    authDomain: 'katkot-5c23e.firebaseapp.com',
    storageBucket: 'katkot-5c23e.appspot.com',
    measurementId: 'G-L3M7NJM1T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxzQfvPMz7vQBhvQ_E6N5QfGiUO-BezI',
    appId: '1:453213686433:android:e0d5ff9448e702ff3b7ee0',
    messagingSenderId: '453213686433',
    projectId: 'katkot-5c23e',
    storageBucket: 'katkot-5c23e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm5nL2xjrKTyPVW-Nd6Qpiqz-OmBpJnSY',
    appId: '1:453213686433:ios:cb938717f68eb9713b7ee0',
    messagingSenderId: '453213686433',
    projectId: 'katkot-5c23e',
    storageBucket: 'katkot-5c23e.appspot.com',
    androidClientId: '453213686433-cmrhjmtmjhtl7scb7c0dflrkqkees79p.apps.googleusercontent.com',
    iosClientId: '453213686433-gb1f0u1ro59vaj8gkasrbru54ka3ga41.apps.googleusercontent.com',
    iosBundleId: 'com.mahmoud.katkotbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm5nL2xjrKTyPVW-Nd6Qpiqz-OmBpJnSY',
    appId: '1:453213686433:ios:5cfe912d187edf1d3b7ee0',
    messagingSenderId: '453213686433',
    projectId: 'katkot-5c23e',
    storageBucket: 'katkot-5c23e.appspot.com',
    androidClientId: '453213686433-cmrhjmtmjhtl7scb7c0dflrkqkees79p.apps.googleusercontent.com',
    iosClientId: '453213686433-13okdfjjh4j43erpq5leb0re2l495d3j.apps.googleusercontent.com',
    iosBundleId: 'com.mahmoud.katkotbot.RunnerTests',
  );
}
